project:
  type: book
  render:
    - "index.qmd"
    - "chapters/*.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

book:
  # Metadata
  author:
    - "Nick Ulle"
    - "Wesley Brooks"
  title: "Intermediate R"
  description: "Reader for the Intermediate R workshop series."
  repo-url: "https://github.com/ucdavisdatalab/workshop_intermediate_r"
  site-url: "https://ucdavisdatalab.github.io/workshop_intermediate_r"
  chapters:
    - "index.qmd"
    - part: "Cleaning & Reshaping Data"
      chapters:
        - "chapters/cleaning-reshaping/01_dates-times.qmd"
        - "chapters/cleaning-reshaping/02_strings.qmd"
        - "chapters/cleaning-reshaping/03_reshaping-data.qmd"
        - "chapters/cleaning-reshaping/04_combining-data.qmd"
    - part: "Visualizing & Analyzing Data"
      chapters:
        - "chapters/03_visualization.qmd"
    - part: "Writing & Debugging Code"
      chapters:
        - "chapters/04_writing_r_scripts.qmd"
        - "chapters/05_debugging.qmd"
    - part: "Thinking in R"
      chapters:
        - "chapters/06_language_fundamentals.qmd"
        - "chapters/07_language_fundamentals_2.qmd"
  appendices:
    - "chapters/appendices/references.qmd"
    - "chapters/appendices/assessment.qmd"

  # Formatting
  date: now
  repo-actions: [issue, source]
  open-graph: true
  twitter-card: true
  favicon: "/images/logos/datalab-logo_square_150x150.png"
  image: "/images/logos/datalab-logo_opengraph_1200x630.png"
  image-alt: "The logo of the UC Davis DataLab."
  sidebar:
    logo: "/images/logos/datalab-logo-full-color-rgb.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .callout.callout-style-default .callout-body {
            padding: 0 1.5rem 0;
          }
          .cell-output-stdout {
            overflow-y: scroll;
            max-height: 30rem;
            margin-bottom: 0.75rem;
          }
          </style>
  # Uncomment to also generate a PDF:
  # pdf: default

# Cache computations from each chapter:
execute:
  freeze: auto
