# Overview {-}

This is the reader for all of UC Davis DataLab's Intermediate R workshop
series. The reader currently has four parts:

1. _Cleaning & Reshaping Data_

2. _Writing & Debugging R Code_

3. _Data Visualization & Analysis in R_

1. _Thinking in R_, which is about understanding how R works, how to diagnose
   and fix bugs in code, and how to estimate and measure performance
   characteristics of code.

Each part is independent and consists of approximately 2 workshop sessions.

After completing these workshops, students will have a better understanding of
language features, packages, and programming strategies, which will enable them
to write more efficient code, be more productive when writing code, and debug
code more effectively.

These workshops are not an introduction to R. Participants are expected to have
prior experience using R, be comfortable with basic R syntax, and to have it
pre-installed and running on their laptops. They are appropriate for motivated
intermediate to advanced users who want a better understanding of base R.
